import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import Nav from '../components/navbar'

export default function Home() {
  const [activeLabel, setActiveLabel] = useState({ id: 0, labelName: 'guest' })
  const [authenticated, setAuthenticated] = useState(false)

  return (
    <div className={styles.container}>
      <Head>
        <title>Download Code Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Nav />
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <Link href="/labels/test-label">
            <a>Test label</a>
          </Link>
        </h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
